### ISSUE TITLE
xface4-terminal is not usable in cube-desktop

### ISSUE THREAD

**Issue by mufeng** [OverC/meta-overc#10]
It shows:

*** VTE ***: Failed to load terminal capabilities from '/etc/termcap'.

some keys are not usable such as 'Enter'.

**Comment by zeddii** [comment]
Yep. I'm seeing the same thing. This was fixed with vte9 put into meta-oe, but it has broken again. I'm using xterm as an alternative for now.

**Comment by mufeng** [comment]
Fix available in upstream. Close.
