### ISSUE TITLE
initramfs init script cannot accept rootfs=LABEL=${LABEL} type

### ISSUE THREAD

**Issue by mufeng** [OverC/meta-overc#15]
When specify root=LABEL=OVERCINSTALLERROOTFS , the init script will fail to mount the root device.

**Comment by lifupan** [comment]
This is caused by Jason's the following commit.
https://github.com/OverC/overc-installer/commit/a471b299515b0c00bb5e8b65e2ba8054b1f1eca8

I'm talking to him to add a loop to wait the LABEL's ready in initramfs's init script.

fupan

**Comment by mufeng** [comment]
I figure out that my problem is the ROOTFS_LABEL variable is too long. This should be fixed by the following commit:
[OverC/overc-installer@b1c39f4](https://github.com/OverC/overc-installer/commit/b1c39f46dc75f66e050b9ca5e298423d1754a6ef)

So closing it.

Thanks for analysis.
Feng
