### ISSUE TITLE
dhcp patch funniness

### ISSUE THREAD

**Issue by masselstine** [OverC/meta-overc#253]
Bruce,

We got some patch tug-o-war going on. I submitted
---
commit 7294f4bb0638dfc48f351e4b7a8b11b89b3b9b76
Author: Mark Asselstine <mark.asselstine@windriver.com>
Date:   Fri Nov 16 11:43:37 2018 -0500

    dhcp: refresh patch context
---

Then you effectively reverted my change with the following commit
---
commit a62a89c4784224dcb9d012df39ccfc122f30dd91
Author: Bruce Ashfield <bruce.ashfield@windriver.com>
Date:   Tue Dec 18 10:48:08 2018 -0500

    dhclient: refresh patch context
---

I am seeing the issue again so I can only assume you haven't updated meta-openembedded. Can you have a look and revert your change if you can confirm my suspicion?

**Comment by zeddii** [comment]
aha. that is probably it. I'll pull and retest and revert as required.

Bruce

On Wed, Jan 16, 2019 at 7:53 PM Mark Asselstine
<notifications@github.com> wrote:
>
> Bruce,
>
> We got some patch tug-o-war going on. I submitted
>
> commit 7294f4b
> Author: Mark Asselstine mark.asselstine@windriver.com
> Date: Fri Nov 16 11:43:37 2018 -0500
>
> dhcp: refresh patch context
>
> ________________________________
>
> Then you effectively reverted my change with the following commit
>
> commit a62a89c
> Author: Bruce Ashfield bruce.ashfield@windriver.com
> Date: Tue Dec 18 10:48:08 2018 -0500
>
> dhclient: refresh patch context
>
> ________________________________
>
> I am seeing the issue again so I can only assume you haven't updated meta-openembedded. Can you have a look and revert your change if you can confirm my suspicion?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
- Thou shalt not follow the NULL pointer, for chaos and madness await
thee at its end
- "Use the force Harry" - Gandalf, Star Trek II

**Comment by zeddii** [comment]
should be fixed now. I reverted my "refresh".
