### ISSUE TITLE
following the guide there is no /opt/installer/

### ISSUE THREAD

**Issue by outbackdingo** [OverC/meta-overc#284]
I followed the guide and created the usb image, booted it, logged into essential, however there is no /opt/installer so I have to ask is this doc correct, or out of date ??

OverC installation
------------------

Once a bootable installer has been created, insert it into the target and
boot. The default USB bootable image runs cube-essential, with the login of
root/root.

After logging into the bootable device, the installer should be run to move
artifacts to their final destination device.

In our cube-install.sh example from above, the following commands should be
run (assuming an installation to a second virtual disk):

 % cd /opt/installer/
 % ./sbin/cubeit-installer images/cube-essential-* vdb #or e.g. sda for hard drive

** Note: The cube installer will destroy all data on the target device, since
         it re-partitions, create filesystems, installs the boot image and
         the rootfs + container filesystems.

         Do not run it against a device with data you cannot afford to lose.

** Note: To create the root filesystem in btrfs, add -b option to cube-install.sh
 % ./sbin/cubeit-installer -b images/cube-essential-* vdb

Once this completes, the device is powered off, and is ready with the OverC
runtime.

**Comment by zeddii** [comment]
I don't think anyone has used the bootable installer for quite some time, it has likely bit rotted to the point of not being useful. Most everyone is generating an image and dd'ing it onto the boot media of the device. 

What device are you attempting to boot -> install to ?

**Comment by outbackdingo** [comment]
can i simply dd the image to /dev/sdb and reboot ? or is there a hd installer for my 1Tb ssd ?
