### ISSUE TITLE
adding storage modules -  target_core_mod tcm_loop target_core_file target_core_user uio

### ISSUE THREAD

**Issue by outbackdingo** [OverC/meta-overc#287]
seems k8s is lacking in the storage areas, storageos requires 
    target_core_mod
    tcm_loop
    target_core_file
    configfs
    target_core_user
    uio

i see configfs ... id like to add the others, can you point me where ? most likely a bb append ?

**Comment by zeddii** [comment]
Correct, this is something you'd do in a bbappend. As to getting the new storage working, that's more of a meta-virtualization question and is best asked there.

**Comment by outbackdingo** [comment]
Yupp, got past this, i know how to resolve storage once these modules are in place. thx
