### ISSUE TITLE
path to upgrade OverC components

### ISSUE THREAD

**Issue by outbackdingo** [OverC/meta-overc#288]
say ive built and deployed overc .. i have desktop build and server .... a few days late i roll a new modified image with changes

cube-builder-genericx86-64-20200716081658.rootfs.tar.bz2

whats the path to upgrading current running images / or overc as a whole in itself, im not finding much in the way of documentation.

**Comment by zeddii** [comment]
The upgrade components were something that Wind River implemented, with plans to get them in to OverC master. Including delta / ostree updates. I haven't seen all the patches for them, but if we raise @masselstine and @jwessel, we can get a better answer.

In other words, OverC doesn't deviate for core OE on the options for upgrading an entire image (there's no one size fits all solution). There's nothing intrinsically baked into it by default, it is something that needs to be added / managed outside of the OverC specific images.

We can of course upgrade the contents of our system containers via packages (if you are building a package feed) or you can update/replace the entire container (with whatever transfer mechanism for the container contents you want). But on the container update mechanism, it is still a few step process (stop, add, start) as I'm about 9 months overdue on making it be a single "update" operation.

**Comment by outbackdingo** [comment]
id be fine with ostree updates if they worked.... id also be inclined to build a package feed, however docs are sparse on doing that, unless i can simply build a package feed useable by dnf based on yocto and host it myself.

lastly is there a forum / mailing list for this stuff so i dont have to keep hounding you with bug reports, as some of this isnt really bugs... just generalized information....

**Comment by masselstine** [comment]
As @zeddii alluded we do have plans for ostree based install and maintenance. I do have something in early stages of work, but as you have seen been lack of activity in the OverC repos I haven't had time to put towards OverC lately. Maybe in August? let's hope. @zeddii did implement 'c3 update' to allow you to upgrade containers, but as he points out, pkg feeds are the only way to upgade cube-essential.

**Comment by outbackdingo** [comment]
sounds good to me... if you need/want help... i am pretty fluent in ostree, aktualizer and OTA mechanisms also.

**Comment by zeddii** [comment]
To answer the mailing list question. We didn't have enough traffic for a dedicated list, so we use freenode and the meta-virtualization list as alternative communication channels.

**Comment by outbackdingo** [comment]
so use meta-virtualization list, good ... which freenode channel ? Yocto ?? 

basically right at the moment i just need builder to work, kubernetes to run and a browser in desktop .... once i achieve this in a prototype, i have time to worry about fixing and enhancing / helping via patches. And I dont want to be a "pain" so i can do some heavy lifting on my own. even docs wise.... as the OverC docs on WR site are some what dated.
