### ISSUE TITLE
cube-desktop-0.2-r0 do_rootfs: Postinstall failure

### ISSUE THREAD

**Issue by outbackdingo** [OverC/meta-overc#295]
NOTE: Executing Tasks
ERROR: cube-desktop-0.2-r0 do_rootfs: Postinstall scriptlets of ['nss'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
Details of the failure are in /var/home/dingo/overc/build/tmp/work/intel_corei7_64-overc-linux/cube-desktop/0.2-r0/temp/log.do_rootfs.
ERROR: Logfile of failure stored in: /var/home/dingo/overc/build/tmp/work/intel_corei7_64-overc-linux/cube-desktop/0.2-r0/temp/log.do_rootfs.1126316
ERROR: Task (/var/home/dingo/overc/meta-overc/meta-cube/recipes-core/images/cube-desktop_0.2.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 11347 tasks of which 9 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /var/home/dingo/overc/meta-overc/meta-cube/recipes-core/images/cube-desktop_0.2.bb:do_rootfs
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by zeddii** [comment]
What revision is your oe-core/poky layer ? That should already have been taken care of by the layer that provides it. I'm able to build cube-desktop against the latest master here.

**Comment by zeddii** [comment]
I should have said meta-oe, above, since that's where nss comes from.

**Comment by zeddii** [comment]
This is being discussed on the oe-devel mailing list. We'll pick up that fix when they get it sorted out.

**Comment by outbackdingo** [comment]
im using poky / master .... updated today :)

**Comment by outbackdingo** [comment]
appears fixed after todays update
