### ISSUE TITLE
maybe poky broke it .... unbuildable dependency chain was: ['cube-essential', 'packagegroup-essential', 'dhcp-client'

### ISSUE THREAD

**Issue by outbackdingo** [OverC/meta-overc#296]
ERROR: Required build target 'cube-essential' has no buildable providers.
Missing or unbuildable dependency chain was: ['cube-essential', 'packagegroup-essential', 'dhcp-client']

**Comment by zeddii** [comment]
yup. This is due to the new bind showing up in oe-core and is expected.

The issue is that the replacement doesn't have dhclient with the same options. 

I'm deciding if carrying a local dhclient recipe will work better, since updating the dhclient calls and scripts will take some time.

**Comment by outbackdingo** [comment]
appears thats youve added dhclient and now it builds so we can close this

**Comment by outbackdingo** [comment]
Welp, it was fixed seems now its broken again... 

gcc/x86_64-overc-linux/10.2.0/ld: privsep-root.o: in function `ps_root_dogetifaddrs':
| /usr/src/debug/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src/privsep-root.c:374: undefined reference to `ALIGN'
| /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/recipe-sysroot-native/usr/bin/x86_64-overc-linux/../../libexec/x86_64-overc-linux/gcc/x86_64-overc-linux/10.2.0/ld: /usr/src/debug/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src/privsep-root.c:375: undefined reference to `ALIGN'
| /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/recipe-sysroot-native/usr/bin/x86_64-overc-linux/../../libexec/x86_64-overc-linux/gcc/x86_64-overc-linux/10.2.0/ld: /usr/src/debug/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src/privsep-root.c:376: undefined reference to `ALIGN'
| /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/recipe-sysroot-native/usr/bin/x86_64-overc-linux/../../libexec/x86_64-overc-linux/gcc/x86_64-overc-linux/10.2.0/ld: /usr/src/debug/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src/privsep-root.c:378: undefined reference to `ALIGN'
| /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/recipe-sysroot-native/usr/bin/x86_64-overc-linux/../../libexec/x86_64-overc-linux/gcc/x86_64-overc-linux/10.2.0/ld: /usr/src/debug/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src/privsep-root.c:380: undefined reference to `ALIGN'
| /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/recipe-sysroot-native/usr/bin/x86_64-overc-linux/../../libexec/x86_64-overc-linux/gcc/x86_64-overc-linux/10.2.0/ld: privsep-root.o:/usr/src/debug/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src/privsep-root.c:382: more undefined references to `ALIGN' follow
| collect2: error: ld returned 1 exit status
| make[1]: *** [Makefile:73: dhcpcd] Error 1
| make[1]: Leaving directory '/var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/dhcpcd-9.1.4/src'
| make: *** [Makefile:24: all] Error 2
| WARNING: /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489:190 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489, line 190
| 	#2: die, /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489, line 171
| 	#3: oe_runmake, /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489, line 160
| 	#4: autotools_do_compile, /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489, line 155
| 	#5: do_compile, /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489, line 150
| 	#6: main, /var/home/dingo/overc/build/tmp/work/corei7-64-overc-linux/dhcpcd/9.1.4-r0/temp/run.do_compile.3979489, line 194
| 
| Backtrace (metadata-relative locations):
| 	#1: bbfatal_log, /var/home/dingo/overc/poky/meta/classes/logging.bbclass, line 72
| 	#2: die, /var/home/dingo/overc/poky/meta/classes/base.bbclass, line 56
| 	#3: oe_runmake, /var/home/dingo/overc/poky/meta/classes/base.bbclass, line 65
| 	#4: autotools_do_compile, /var/home/dingo/overc/poky/meta/classes/autotools.bbclass, line 243
| 	#5: do_compile, autogenerated, line 2
ERROR: Task (/var/home/dingo/overc/poky/meta/recipes-connectivity/dhcpcd/dhcpcd_9.1.4.bb:do_compile) failed with exit code '1'
Waiting for 2 running tasks to finish:
0: boost-1.74.0-r0 do_compile - 31m19s (pid 2504239)
1: nodejs-native-12.18.3-r0 do_compile - 21m34s (pid 3085943)

**Comment by outbackdingo** [comment]
appears fixed again...!
