### ISSUE TITLE
consul: QA Issue: No GNU_HASH in the elf binary

### ISSUE THREAD

**Issue by masselstine** [OverC/meta-overc#50]
When building we see the following QA warning:

WARNING: consul-git-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: '/home/mark/build/overc/tmp/work/core2-64-overc-linux/consul/git-r0/packages-split/consul/usr/bin/consul' [ldflags]

**Comment by jwessel** [comment]
This change removes the QA warning but does not fix the underlying problem of passing along the LDFLAGS.  The go cross environment does makes it problematic to fix the root cause so it will be left for another day.
