### ISSUE TITLE
QA warning with pulsar-8 branch

### ISSUE THREAD

**Issue by jiazhang0** [OverC/meta-overc#74]
WARNING: QA Issue: lxc: Files/directories were installed but not shipped in any package:
  /usr/share/lua
  /usr/share/lua/lxc.lua
  /usr/lib64/lua/lxc/core.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lxc: 3 installed and not shipped files. [installed-vs-shipped]

**Comment by masselstine** [comment]
There is a fix proposed for this on the meta-virt mailing list. If this is merged we can close this issue.

https://lists.yoctoproject.org/pipermail/meta-virtualization/2017-March/002490.html

**Comment by masselstine** [comment]
The fixed I mentioned yesterday has been merged.

http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=ea05b2693aa6eae10a5f59aa7a47e52b4c4b4acd
