### ISSUE TITLE
systemd-networkd out of working on master-oci

### ISSUE THREAD

**Issue by yunguowei** [OverC/meta-overc#82]
On cube-server, systemd-networkd failed:

root@cube-server:~# systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-05-25 04:54:51 EDT; 4min 9s ago
     Docs: man:systemd-networkd.service(8)
  Process: 671 ExecStart=/lib/systemd/systemd-networkd (code=exited, status=1/FAILURE)
 Main PID: 671 (code=exited, status=1/FAILURE)
   Status: "Shutting down..."

May 25 04:54:51 cube-server systemd[1]: Failed to start Network Service.
May 25 04:54:51 cube-server systemd[1]: systemd-networkd.service: Unit entered failed state.
May 25 04:54:51 cube-server systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
May 25 04:54:51 cube-server systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart.
May 25 04:54:51 cube-server systemd[1]: Stopped Network Service.
May 25 04:54:51 cube-server systemd[1]: systemd-networkd.service: Start request repeated too quickly.
May 25 04:54:51 cube-server systemd[1]: Failed to start Network Service.
May 25 04:54:51 cube-server systemd[1]: systemd-networkd.service: Unit entered failed state.
May 25 04:54:51 cube-server systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
root@cube-server:~# systemctl status systemd-networkd^C
root@cube-server:~# /lib/systemd/systemd-networkd
Failed to increase capabilities: Operation not permitted

Sounds to be permission issue.

**Comment by zeddii** [comment]
We are not tracking issues against master-oci.

that being said, networking is not handled by systemd in theses containers, so we don't care.
